version: '2'

services:
  app:
    image: skynet/core:latest
    restart: unless-stopped
    depends_on:
    - db
    ports:
    - '32761:32761'
    volumes:
    - data/skynetconfig.json:/skynetconfig.json
    - data/firebase-service-account.json:/app/firebase-service-account.json
  web:
    image: skynet/web:latest
    restart: unless-stopped
    depends_on:
    - db
    ports:
    - '8080:80'
    volumes:
    - data/skynetconfig.json:/skynetconfig.json
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - data/mysql:/var/lib/mysql
