// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkynetServer.Entities;

namespace SkynetServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181127205126_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SkynetServer.Entities.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName")
                        .IsRequired();

                    b.HasKey("AccountId");

                    b.HasAlternateKey("AccountName");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SkynetServer.Entities.Channel", b =>
                {
                    b.Property<long>("ChannelId");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SkynetServer.Entities.Message", b =>
                {
                    b.Property<long>("ChannelId");

                    b.Property<long>("MessageId");

                    b.Property<DateTime>("DispatchTime");

                    b.HasKey("ChannelId", "MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SkynetServer.Entities.Message", b =>
                {
                    b.HasOne("SkynetServer.Entities.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
